version: "3.7"
volumes:
  mongovolume: {}
  letsencrypt: {}
  upload: {}
services:
  mongo:
    image: mongo:latest
    volumes:
      - ../secrets/users.js:/docker-entrypoint-initdb.d/users.js:ro
      - mongovolume:/data/db
    command:
      - "--bind_ip_all"
    env_file:
      # Provides:
      # - MONGO_INITDB_DATABASE
      # - MONGO_INITDB_ROOT_USERNAME
      # - MONGO_INITDB_ROOT_PASSWORD
      # Only required for initialization when /data/db is empty
      - ../secrets/mongo.env
    restart: unless-stopped
  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - upload:/upload
    env_file:
      # Provides: MONGO_URL=mongodb://ADMIN_USER_NAME:ADMIN_PASSWORD@mongo:27017/DATABASE
      - ../secrets/app.env
    environment:
      - APP_ENV="prod"
      - APP_DEBUG="False"
      - APP_PORT=5000
    ports:
      - "5000:5000"
    restart: unless-stopped
