name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/main.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.4.6
        env:
          heroku_app_name: freshworks
          heroku_email: "campaigntestv@gmail.com"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
