name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push to Heroku
        uses: jctaveras/heroku-deploy@v2.1.3
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "freshworks"
          email: "campaigntestv@gmail.com"
          dockerfile_path: './app' 
          options: ''
          formation: ''
